### ISSUE TITLE
API: PATCH broken on my-synclists

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#269]
PATCH is broken on the my-synclists endpoint. Right now it throws a 500

```
api_1               | Traceback (most recent call last):
api_1               |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
api_1               |     response = get_response(request)
api_1               |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
api_1               |     response = self.process_exception_by_middleware(e, request)
api_1               |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
api_1               |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api_1               |   File "/venv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api_1               |     return view_func(*args, **kwargs)
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
api_1               |     return self.dispatch(request, *args, **kwargs)
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
api_1               |     response = self.handle_exception(exc)
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
api_1               |     self.raise_uncaught_exception(exc)
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
api_1               |     raise exc
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
api_1               |     response = handler(request, *args, **kwargs)
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/mixins.py", line 82, in partial_update
api_1               |     return self.update(request, *args, **kwargs)
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/mixins.py", line 67, in update
api_1               |     serializer.is_valid(raise_exception=True)
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py", line 235, in is_valid
api_1               |     self._validated_data = self.run_validation(self.initial_data)
api_1               |   File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py", line 430, in run_validation
api_1               |     value = self.to_internal_value(data)
api_1               |   File "/src/galaxy_ng/galaxy_ng/app/api/ui/serializers/synclist.py", line 50, in to_internal_value
api_1               |     data['groups'] = self._sanitize_groups(groups)
api_1               |   File "/src/galaxy_ng/galaxy_ng/app/api/ui/serializers/synclist.py", line 40, in _sanitize_groups
api_1               |     for group_name in group_names:
api_1               | TypeError: 'NoneType' object is not iterable
```

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/315 WIP includes this fix.

**Comment by alikins** [comment]
No work needed for this that isn't already part of #315

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/315

**Comment by alikins** [comment]
Should be fixed with https://github.com/alikins/galaxy_ng/commit/6348ce4f88331bba12306db1eb259ab88605f195
