### ISSUE TITLE
400 bad request from automation hub - bad SSO token?

### ISSUE THREAD

**Issue by pabelanger** [ansible/galaxy_ng#371]
## Bug Report
For some unknown reason, we started to get 400 bad request exceptions when publishing to AH using ansible-galaxy CLI.  After some back and forth, it seems the SSO token was bad, when we replaced it things started to work again.

We'd like to understand why the token went bad, if expired why we didn't get  a notification about it, and to get a better error message in ansible-galaxy then exception raised.

##### ACTUAL RESULTS

```
2020-08-07 17:59:00.286204 | LOOP [upload-ansible-collection-fork : Publish collection to Ansible Galaxy / Automation Hub]
2020-08-07 17:59:02.242088 | localhost | [DEPRECATION WARNING]: Setting verbosity before the arg sub command is
2020-08-07 17:59:02.242355 | localhost | deprecated, set the verbosity after the sub command. This feature will be
2020-08-07 17:59:02.242429 | localhost | removed in version 2.13. Deprecation warnings can be disabled by setting
2020-08-07 17:59:02.242523 | localhost | deprecation_warnings=False in ansible.cfg.
2020-08-07 17:59:02.242591 | localhost | ansible-galaxy 2.9.11
2020-08-07 17:59:02.242656 | localhost |   config file = /var/lib/zuul/builds/9e1d9898a0cc46fc8651237b74916e1f/work/tmp/ansible.0zkd_uqg.cfg
2020-08-07 17:59:02.242722 | localhost |   configured module search path = ['/var/lib/zuul/builds/9e1d9898a0cc46fc8651237b74916e1f/work/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
2020-08-07 17:59:02.242798 | localhost |   ansible python module location = /opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible
2020-08-07 17:59:02.242862 | localhost |   executable location = /opt/venv/zuul-ansible/2.9.11/bin/ansible-galaxy
2020-08-07 17:59:02.242923 | localhost |   python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
2020-08-07 17:59:02.242999 | localhost | Using /var/lib/zuul/builds/9e1d9898a0cc46fc8651237b74916e1f/work/tmp/ansible.0zkd_uqg.cfg as config file
2020-08-07 17:59:02.243062 | localhost | ERROR! Unexpected Exception, this is probably a bug: HTTP Error 400: Bad Request
2020-08-07 17:59:02.243123 | localhost | the full traceback was:
2020-08-07 17:59:02.243184 | localhost |
2020-08-07 17:59:02.243245 | localhost | Traceback (most recent call last):
2020-08-07 17:59:02.243305 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/bin/ansible-galaxy", line 123, in <module>
2020-08-07 17:59:02.243366 | localhost |     exit_code = cli.run()
2020-08-07 17:59:02.243426 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 376, in run
2020-08-07 17:59:02.243487 | localhost |     context.CLIARGS['func']()
2020-08-07 17:59:02.243548 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 1032, in execute_publish
2020-08-07 17:59:02.243624 | localhost |     publish_collection(collection_path, self.api, wait, timeout)
2020-08-07 17:59:02.243683 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/collection.py", line 412, in publish_collection
2020-08-07 17:59:02.243760 | localhost |     import_uri = api.publish_collection(collection_path)
2020-08-07 17:59:02.243821 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/api.py", line 56, in wrapped
2020-08-07 17:59:02.243881 | localhost |     data = self._call_galaxy(n_url, method='GET', error_context_msg=error_context_msg)
2020-08-07 17:59:02.243952 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/api.py", line 192, in _call_galaxy
2020-08-07 17:59:02.244019 | localhost |     self._add_auth_token(headers, url, required=auth_required)
2020-08-07 17:59:02.244080 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/api.py", line 222, in _add_auth_token
2020-08-07 17:59:02.244142 | localhost |     headers.update(self.token.headers())
2020-08-07 17:59:02.244203 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/token.py", line 94, in headers
2020-08-07 17:59:02.244264 | localhost |     headers['Authorization'] = '%s %s' % (self.token_type, self.get())
2020-08-07 17:59:02.244324 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/token.py", line 81, in get
2020-08-07 17:59:02.244385 | localhost |     http_agent=user_agent())
2020-08-07 17:59:02.244446 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/module_utils/urls.py", line 1390, in open_url
2020-08-07 17:59:02.244507 | localhost |     unredirected_headers=unredirected_headers)
2020-08-07 17:59:02.244568 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/module_utils/urls.py", line 1294, in open
2020-08-07 17:59:02.244629 | localhost |     r = urllib_request.urlopen(*urlopen_args)
2020-08-07 17:59:02.244690 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
2020-08-07 17:59:02.244750 | localhost |     return opener.open(url, data, timeout)
2020-08-07 17:59:02.244810 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
2020-08-07 17:59:02.244870 | localhost |     response = meth(req, response)
2020-08-07 17:59:02.244954 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
2020-08-07 17:59:02.245033 | localhost |     'http', request, response, code, msg, hdrs)
2020-08-07 17:59:02.245100 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
2020-08-07 17:59:02.245161 | localhost |     return self._call_chain(*args)
2020-08-07 17:59:02.245222 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
2020-08-07 17:59:02.245281 | localhost |     result = func(*args)
2020-08-07 17:59:02.245342 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
2020-08-07 17:59:02.245402 | localhost |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2020-08-07 17:59:02.245461 | localhost | urllib.error.HTTPError: HTTP Error 400: Bad Request
2020-08-07 17:59:02.245535 | localhost | [DEPRECATION WARNING]: Setting verbosity before the arg sub command is
2020-08-07 17:59:02.245599 | localhost | deprecated, set the verbosity after the sub command. This feature will be
2020-08-07 17:59:02.245674 | localhost | removed in version 2.13. Deprecation warnings can be disabled by setting
2020-08-07 17:59:02.245732 | localhost | deprecation_warnings=False in ansible.cfg.
2020-08-07 17:59:02.245791 | localhost | ansible-galaxy 2.9.11
2020-08-07 17:59:02.245849 | localhost |   config file = /var/lib/zuul/builds/9e1d9898a0cc46fc8651237b74916e1f/work/tmp/ansible.0zkd_uqg.cfg
2020-08-07 17:59:02.245910 | localhost |   configured module search path = ['/var/lib/zuul/builds/9e1d9898a0cc46fc8651237b74916e1f/work/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
2020-08-07 17:59:02.245999 | localhost |   ansible python module location = /opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible
2020-08-07 17:59:02.246062 | localhost |   executable location = /opt/venv/zuul-ansible/2.9.11/bin/ansible-galaxy
2020-08-07 17:59:02.246122 | localhost |   python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
2020-08-07 17:59:02.246183 | localhost | Using /var/lib/zuul/builds/9e1d9898a0cc46fc8651237b74916e1f/work/tmp/ansible.0zkd_uqg.cfg as config file
2020-08-07 17:59:02.246244 | localhost | ERROR! Unexpected Exception, this is probably a bug: HTTP Error 400: Bad Request
2020-08-07 17:59:02.246304 | localhost | the full traceback was:
2020-08-07 17:59:02.246364 | localhost |
2020-08-07 17:59:02.246424 | localhost | Traceback (most recent call last):
2020-08-07 17:59:02.246776 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/bin/ansible-galaxy", line 123, in <module>
2020-08-07 17:59:02.246860 | localhost |     exit_code = cli.run()
2020-08-07 17:59:02.246937 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 376, in run
2020-08-07 17:59:02.247014 | localhost |     context.CLIARGS['func']()
2020-08-07 17:59:02.247076 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 1032, in execute_publish
2020-08-07 17:59:02.247137 | localhost |     publish_collection(collection_path, self.api, wait, timeout)
2020-08-07 17:59:02.247198 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/collection.py", line 412, in publish_collection
2020-08-07 17:59:02.247259 | localhost |     import_uri = api.publish_collection(collection_path)
2020-08-07 17:59:02.247320 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/api.py", line 56, in wrapped
2020-08-07 17:59:02.247381 | localhost |     data = self._call_galaxy(n_url, method='GET', error_context_msg=error_context_msg)
2020-08-07 17:59:02.247442 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/api.py", line 192, in _call_galaxy
2020-08-07 17:59:02.247503 | localhost |     self._add_auth_token(headers, url, required=auth_required)
2020-08-07 17:59:02.247563 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/api.py", line 222, in _add_auth_token
2020-08-07 17:59:02.247625 | localhost |     headers.update(self.token.headers())
2020-08-07 17:59:02.247708 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/token.py", line 94, in headers
2020-08-07 17:59:02.247770 | localhost |     headers['Authorization'] = '%s %s' % (self.token_type, self.get())
2020-08-07 17:59:02.247828 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/galaxy/token.py", line 81, in get
2020-08-07 17:59:02.247886 | localhost |     http_agent=user_agent())
2020-08-07 17:59:02.247973 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/module_utils/urls.py", line 1390, in open_url
2020-08-07 17:59:02.248036 | localhost |     unredirected_headers=unredirected_headers)
2020-08-07 17:59:02.248097 | localhost |   File "/opt/venv/zuul-ansible/2.9.11/lib/python3.6/site-packages/ansible/module_utils/urls.py", line 1294, in open
2020-08-07 17:59:02.248158 | localhost |     r = urllib_request.urlopen(*urlopen_args)
2020-08-07 17:59:02.248218 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
2020-08-07 17:59:02.248278 | localhost |     return opener.open(url, data, timeout)
2020-08-07 17:59:02.248338 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
2020-08-07 17:59:02.248398 | localhost |     response = meth(req, response)
2020-08-07 17:59:02.248458 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
2020-08-07 17:59:02.248538 | localhost |     'http', request, response, code, msg, hdrs)
2020-08-07 17:59:02.248629 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
2020-08-07 17:59:02.248723 | localhost |     return self._call_chain(*args)
2020-08-07 17:59:02.248787 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
2020-08-07 17:59:02.248846 | localhost |     result = func(*args)
2020-08-07 17:59:02.248906 | localhost |   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
2020-08-07 17:59:02.248981 | localhost |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2020-08-07 17:59:02.249043 | localhost | urllib.error.HTTPError: HTTP Error 400: Bad Request
2020-08-07 17:59:02.249167 | localhost | ok: Item: {'path': '/var/lib/zuul/builds/9e1d9898a0cc46fc8651237b74916e1f/work/logs/artifacts/vyos-vyos-1.0.3.tar.gz', 'mode': '0664', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 3000, 'gid': 3000, 'size': 277509, 'inode': 4404644, 'dev': 64513, 'nlink': 1, 'atime': 1596823131.9355824, 'mtime': 1596823124.7833407, 'ctime': 1596823131.9555829, 'gr_name': 'zuul', 'pw_name': 'zuul', 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': True, 'rgrp': True, 'xgrp': False, 'woth': False, 'roth': True, 'xoth': False, 'isuid': False, 'isgid': False} Result: 250
2020-08-07 17:59:02.304190 | 
```

**Comment by chouseknecht** [comment]
Migrated to Jira: AAH-50
