### ISSUE TITLE
UI: Certification dashboard fail

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#376]
In standalone mode, when the certification repository name and distribution are set to "published", the certification dashboard throws an error when the "Certify" button is clicked. 

Steps to reproduce:

1. Create a standalone instance with `galaxy_require_content_approval: "True"`
2. Create a namespace on the new server
3. Upload a collection to the new namespace 
4. Locate the collection on the Certification dashboard, and click the "Certify" button

Results: 

Request to https://<server>/api/galaxy/v3/_ui/collection-versions/cisco/ios/1.0.2/certified/ returns the following:

`{"errors":[{"status":"404","code":"not_found","title":"Not found."}]}`

Expected:

The collection is certified and becomes visible on the Collections page.

**Comment by chouseknecht** [comment]
@ZitaNemeckova 

Tested with a fresh install of latest release (4.2.0b1). 

The endpoint that fails is:

```
https://<server>/api/galaxy/v3/collections/newswangerd/collection_demo/versions/1.0.10/move/staging/published/
```

There error is: 

```
Server Error (500)
```

Traceback from the system log:

```
pulp: django.request:ERROR: Internal Server Error: /api/galaxy/v3/collections/newswangerd/collection_demo/versions/1.0.10/move/staging/published/
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]: Traceback (most recent call last):
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    response = get_response(request)
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    response = self.process_exception_by_middleware(e, request)
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    return view_func(*args, **kwargs)
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    return self.dispatch(request, *args, **kwargs)
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    response = self.handle_exception(exc)
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    self.raise_uncaught_exception(exc)
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    raise exc
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    response = handler(request, *args, **kwargs)
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/galaxy_ng/app/api/v3/viewsets/collection.py", line 326, in move_content
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]:    "curate_all_synclist_repository_task_id": curate_task.id,
Sep 16 12:04:00 ip-192-168-2-43 gunicorn[42996]: UnboundLocalError: local variable 'curate_task' referenced before assignment
```

**Comment by hendersonreed** [comment]
Closing, this is resolved.
