### ISSUE TITLE
Attempting to reject an already certified collection causes UnboundLocalError

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#449]
##### SUMMARY
When trying to reject a collection that was already auto-certified the attempt fails with a 500 response from the API and a traceback about an UnboundLocalError (in the traceback below)

##### STEPS TO REPRODUCE

- Enable auto-certification
- Upload a collection
- Go to the certification dashboard and select "Reject" in the menu options for the collection

##### EXPECTED RESULTS

For the collection version to be rejected and hidden from the collection version list.

##### ACTUAL RESULTS

```
Traceback:

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/viewsets.py" in view
  114.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/views.py" in dispatch
  505.             response = self.handle_exception(exc)

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/views.py" in handle_exception
  465.             self.raise_uncaught_exception(exc)

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/views.py" in raise_uncaught_exception
  476.         raise exc

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/rest_framework/views.py" in dispatch
  502.             response = handler(request, *args, **kwargs)

File "/usr/local/lib/pulp/lib64/python3.6/site-packages/galaxy_ng/app/api/v3/viewsets/collection.py" in move_content
  326.                 "curate_all_synclist_repository_task_id": curate_task.id,

Exception Type: UnboundLocalError at /api/galaxy/v3/collections/autohubtest2/collection_dep_a_irlwylhj/versions/1.0.0/move/published/rejected/
Exception Value: local variable 'curate_task' referenced before assignment
Request information:
```

**Comment by ironfroggy** [comment]
More testing reveals isn't related to rejecting certified content specifically. This affects ALL certification state changes on standalone.

**Comment by awcrosby** [comment]
While something like #453 is needed to fix this bug, it's worth noting the UI certification process moves the collection version to `published` and if `GALAXY_API_DEFAULT_DISTRIBUTION_BASE_PATH` is not `published` you will see this bug.

**Comment by Spredzy** [comment]
I am facing the same issue when trying to certify a certification

```
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: pulp: django.request:ERROR: Internal Server Error: /api/galaxy/v3/collections/awx/awx/versions/14.1.
0/move/staging/published/                                                                                                                                       
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: Traceback (most recent call last):                             
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner 
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: response = get_response(request)                                                                    Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: response = self.process_exception_by_middleware(e, request)                                         Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: return view_func(*args, **kwargs)            
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: return self.dispatch(request, *args, **kwargs)                    
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: response = self.handle_exception(exc)
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: self.raise_uncaught_exception(exc)
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_excepti
on
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: raise exc
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: response = handler(request, *args, **kwargs)
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: File "/usr/lib/python3.6/site-packages/galaxy_ng/app/api/v3/viewsets/collection.py", line 326, in mo
ve_content
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: "curate_all_synclist_repository_task_id": curate_task.id,
Sep 16 08:01:36 ip-10-0-8-243.ec2.internal gunicorn[32605]: UnboundLocalError: local variable 'curate_task' referenced before assignment
```

**Comment by Spredzy** [comment]
This has been fixed for me. I am using b2 andd I am not facing this issue no more.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
