### ISSUE TITLE
Collection endpoint on c.rh.c returns 500

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#454]
The following endpoint results in a 500 error: `https://cloud.redhat.com/api/automation-hub/v3/collections/cisco/ios/`

The traceback from the server side follows:

```

2020-09-15 19:43:11,265 ERROR django.request: Internal Server Error: /api/automation-hub/v3/collections/cisco/ios/
Traceback (most recent call last):
  File "/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/venv/lib64/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/venv/lib64/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/venv/lib64/python3.6/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/venv/lib64/python3.6/site-packages/rest_framework/renderers.py", line 657, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/venv/lib64/python3.6/site-packages/rest_framework/renderers.py", line 542, in get_raw_data_form
    if not self.show_form_for_method(view, method, request, instance):
  File "/venv/lib64/python3.6/site-packages/rest_framework/renderers.py", line 434, in show_form_for_method
    view.check_object_permissions(request, obj)
  File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 343, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/app/galaxy_ng/app/api/permissions.py", line 55, in has_object_permission
    request, view, obj)
  File "/app/galaxy_ng/app/api/permissions.py", line 45, in has_object_permission
    return IsNamespaceOwner().has_object_permission(request, view, obj)
  File "/app/galaxy_ng/app/api/permissions.py", line 38, in has_object_permission
    return namespace.groups.filter(pk__in=request.user.groups.all()).exists()
AttributeError: 'str' object has no attribute 'groups'
```

**Comment by ironfroggy** [comment]
Possible cause:

it only affects when you hit the API endpoint in the browser, it does not affect API client behavior.



request.user can in some cases be turned into a str as part of Django template rendering. Which only happens when you're hitting it through the browser. If you hit it with Accept: application/json it never renders that page, and request.user is not turned into a string

**Comment by awcrosby** [comment]
Note: this is fixed in CI with latest code base, once that is deployed it will be fixed in Prod.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
