### ISSUE TITLE
Importer: ansible-test error inside pylint on openshift

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#64]
When `ansible-test sanity` runs during import, it runs in an openshift container and the `pylint` test is run. For collection `ibm.spectrum_virtualize`, `pylint` calls `multiprocessing.connection.recv` which hits an EOF error when unpickling an object.

Environment(s) seen with issue: AH Prod and AH QA
Environment(s) seen without issue: running importer in cli mode, running `ansible-test sanity -t pylint --docker` locally

Traceback from AH QA import:
```
...
Running sanity test 'pep8' with Python 3.6 
Running sanity test 'pylint' with Python 3.6 
ERROR: Command "/usr/bin/python3.6 -m pylint --jobs 0 --reports n --max-line-length 160 --rcfile /usr/local/lib/python3.6/dist-packages/ansible_test/_data/sanity/pylint/config/collection.cfg --output-format json --load-plugins blacklist,deprecated,string_format tests/unit/plugins/module_utils/test_ibm_svc_utils.py tests/unit/plugins/modules/test_ibm_svc_host.py tests/unit/plugins/modules/test_ibm_svc_info.py tests/unit/plugins/modules/test_ibm_svc_mdisk.py tests/unit/plugins/modules/test_ibm_svc_mdiskgrp.py tests/unit/plugins/modules/test_ibm_svc_vdisk.py tests/unit/plugins/modules/test_ibm_svc_vol_map.py" returned exit status 1. 
>>> Standard Error 
Process ChildLinter-2: 
Traceback (most recent call last): 
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap 
self.run() 
File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 241, in run 
for file_or_module in iter(tasks_queue.get, "STOP"): 
File "<string>", line 2, in get 
File "/usr/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod 
kind, result = conn.recv() 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv 
buf = self._recv_bytes() 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes 
buf = self._recv(4) 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv 
raise EOFError 
EOFError 
Process ChildLinter-4: 
Traceback (most recent call last): 
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap 
self.run() 
File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 241, in run 
for file_or_module in iter(tasks_queue.get, "STOP"): 
File "<string>", line 2, in get 
File "/usr/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod 
kind, result = conn.recv() 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv 
buf = self._recv_bytes() 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes 
buf = self._recv(4) 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv 
raise EOFError 
EOFError 
internal error with sending report for module ['tests/unit/plugins/modules/test_ibm_svc_info.py'] 
[Errno 32] Broken pipe 
Process ChildLinter-3: 
Traceback (most recent call last): 
File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 244, in run 
results_queue.put(result) 
File "<string>", line 2, in put 
File "/usr/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod 
conn.send((self._id, methodname, args, kwds)) 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send 
self._send_bytes(_ForkingPickler.dumps(obj)) 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes 
self._send(header + buf) 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send 
n = write(self._handle, buf) 
BrokenPipeError: [Errno 32] Broken pipe 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap 
self.run() 
File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 252, in run 
...
```

**Comment by awcrosby** [comment]
Another similar symptom: during pylint the job will hit a `OOMKilled` error and terminate. For the end user this shows `Running sanity test 'pylint' with Python 3.6` then `Done` without displaying any error and without running any further sanity tests. This error needs to be surfaced to the logs.

Also working on increasing the cpu and memory of the job

**Comment by chouseknecht** [comment]
Development work completed. CI deployment blocked by #10

**Comment by awcrosby** [comment]
Note: `galaxy-importer==0.2.0` fixed this for QA but not in Prod

**Comment by ironfroggy** [comment]
@awcrosby  Has this been deployed to only QA or also to CI?

**Comment by awcrosby** [comment]
It has been deployed to both CI and QA.

**Comment by awcrosby** [comment]
While we noticed this issue in Prod after our fix was deployed, in checking the logs the issue actually occurred before the fix was deployed.
