### ISSUE TITLE
Git-based versioning in galaxy_ng package breaks on PyPI install (galaxy_ng@4.2.0a1)

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#98]
Installing the package from PyPI fails because it relies on git to determine the version, which is not present. Fails with `"Cannot determine git version string"`.

```
(automation-hub) [calvin@localhost ansible-hub-ui]$ pip install -U galaxy_ng
Collecting galaxy_ng
  Using cached galaxy-ng-4.2.0a1.tar.gz (45 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/calvin/.local/share/virtualenvs/automation-hub/bin/python3 /home/calvin/.local/share/virtualenvs/automation-hub/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpnkc3crru
       cwd: /tmp/pip-install-bm0zg8qk/galaxy-ng
  Complete output (33 lines):
  fatal: not a git repository (or any parent up to mount point /)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  Traceback (most recent call last):
    File "/tmp/pip-install-bm0zg8qk/galaxy-ng/galaxy_ng/version.py", line 17, in get_git_version
      'git', 'describe', '--tags', '--always', '--match', TAG_PREFIX + '*']
    File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/usr/lib64/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--always', '--match', 'v*']' returned non-zero exit status 128.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/calvin/.local/share/virtualenvs/automation-hub/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/calvin/.local/share/virtualenvs/automation-hub/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/calvin/.local/share/virtualenvs/automation-hub/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-gffz213z/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 148, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-gffz213z/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-gffz213z/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 250, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-gffz213z/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 53, in <module>
      version=version.get_git_version(),
    File "/tmp/pip-install-bm0zg8qk/galaxy-ng/galaxy_ng/version.py", line 20, in get_git_version
      raise RuntimeError('Cannot determine git version string.')
  RuntimeError: Cannot determine git version string.
```

**Comment by cutwater** [comment]
@newswangerd We should switch distribution format from `sdist` to `wheel`.
